[project]
name = "wechatpublisher"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pdf2image>=1.17.0",
    "pymupdf>=1.26.3",
    "pypdf2>=3.0.1",
    "pytest>=8.4.1",
    "reportlab>=4.4.3",
]
